@startuml
!include DEFS.puml

autoactivate on
actor Usuário
Usuário -> MCU : Aciona o botão de parada
hnote over Esteira : Ligada
MCU -> MCU : Dispositivo de manobra
MCU -> Esteira : Desliga esteira
hnote over Esteira : Desligada
return Atualiza o display
MCU -> MCU : Emite sinal sonoro e luminoso
MCU -> Monitor : Envia dados para o IHM
Monitor -> Usuário : Exibe status da esteira
hnote over Esteira : Manutenção
Usuário -> Monitor : Rearme pelo IHM
hnote over Esteira : Ligada

legend top
 **Diagrama de Sequência - Módulo de Controle (MC) - Emergência**
end legend

footer


  **Casos de Uso cobertos:**
   **- MC-003:** Lógica de Segurança (NR-12)
end footer  


@enduml