@startuml

<style>
footer {
  HorizontalAlignment left
  FontSize 14
  FontColor blue
  FontName Arial
  Margin 20
  Padding 10
}

legend {
  HorizontalAlignment center
  FontSize 16
  FontColor Blue
  FontName Arial
  Margin 20
  Padding 10
}
</style>


'Parametros de cor:
skinparam backgroundColor #EEEBDC
skinparam handwritten true
skinparam sequenceArrowColor DeepSkyBlue
skinparam sequenceActorBorderColor DeepSkyBlue
skinparam sequenceLifeLineBorderColor blue
skinparam sequenceLifeLineBackgroundColor #A9DCDF
skinparam sequenceParticipantBorderColor DeepSkyBlue
skinparam sequenceParticipantBackgroundColor DodgerBlue
skinparam sequenceParticipantFontName Impact
skinparam sequenceParticipantFontSize 17
skinparam sequenceParticipantFontColor #A9DCDF
skinparam sequenceActorBackgroundColor aqua
skinparam sequenceActorFontColor DeepSkyBlue
skinparam sequenceActorFontSize 17
skinparam sequenceActorFontName Aapex

autoactivate on
Hide footbox

actor "Sensor Óptico"

"Sensor Óptico" -> MCU: Detecta produto no ponto de inspeção
activate MCU #000000


participant "MCU" as MCU
participant Câmera
participant "Módulo Edge\n(Processamento/Gateway)" as EDGE
participant "MDC/Cloud\n(Servidor SFTP)" as MDC

MCU -> Câmera : Produto detectado\n(Ponto de inspeção)
activate Câmera
EDGE --> Câmera : Solicita captura \n($1920\times1080$ px)
Câmera -> EDGE : Envia imagem RAW
deactivate Câmera

EDGE --> EDGE : Processa imagem (Compressão JPEG 85%)
hnote over EDGE : Prepara para transmissão

EDGE -> MDC : Transmite foto via SFTP (criptografado)
MDC --> EDGE : Confirmação de recebimento (ACK)

EDGE --> MCU : Resposta: Captura e envio concluídos
note over EDGE, MDC: Tempo total < 2 segundos

legend top
 **Fluxograma de Operação: Captura de Fotografia (MC-006)**
end legend

footer
  **Casos de Uso cobertos:**
   - **MC-006**: Captura de Fotografia para Controle de Qualidade
end footer  

@endumlg