@startuml
!include DEFS.puml

actor "Operador" as OP
actor "Supervisor" as SP
boundary "IHM"
participant "MCU"

/'
O sistema DEVE controlar o acesso por níveis de usuário. Será
considerado atendido quando existirem, no mínimo, dois perfis: "Operador"
(apenas para operação básica) e "Supervisor" (para configuração de
parâmetros e reset de falhas).
'/

'======================================================
'                      Inicio
'======================================================
activate IHM
activate MCU
OP -> IHM: Envio de um comando sem a autorização para execução
IHM --> OP: A ação inválida é negada
hnote over IHM: Recepção e envio de dados

OP -> IHM: Envio de um comando com a autorização para execução
IHM --> OP: A ação permitida é executada
hnote over MCU: Verifica os níveis de autorização do usuário

IHM -> MCU: Envio da demanda
MCU --> IHM: Se autorizado, permite.
MCU --> IHM: Se não autorizado, bloqueia.
'-----------------------------
SP -> IHM: Envio de um comando qualquer
IHM --> SP: A ação é executada
deactivate IHM

/'
activate MCU
MG -> MCU: Repasse dos dados
MCU -> IHM: Exibição
IHM -> "Operador": Visualização
deactivate MCU

hnote over MCU: Processamento das informações

hnote over IHM: Em menos de 2s a notificação sonora/visual ocorre através da IHM
'/

'=====================================================
'Notas:
'=====================================================

legend top
**Diagrama de sequência - Módulo de Interface e Operação (MIO) - IHM Operacional**
end legend

footer


**Casos de Uso cobertos**:
 - **MIO-003** Autenticação de Usuários
end footer



@enduml