@startuml
!include DEFS.puml

actor Operador
participant "Linha de produção" as A
participant "Contagem em tempo real" as B
participant "Status do sistema" as C

'======================================================
'                      Inicio
'======================================================

'Comando de iniciar/parar:
Operador -> A: Iniciar/Parar
activate A
'------------------------------------------------------

'Solicitar Contagem
Operador -> B: Solicitar
activate B
'------------------------------------------------------

'Solicitar o Status 
Operador-> C: Solicitar
activate C
'------------------------------------------------------

C --> Operador: Mostrar Status
deactivate C
'------------------------------------------------------

B --> Operador: Mostrar a contagem
deactivate B
'------------------------------------------------------

A --> Operador: Operação finalizada
deactivate A
'------------------------------------------------------


'=====================================================
'Notas:
'=====================================================

legend top
**Diagrama de sequência - Módulo de Interface e Operação (MIO) - IHM Operacional**
end legend

footer


**Casos de Uso cobertos**:
 - **MIO-001** Interface de operação (IHM)
end footer



@enduml