@startuml
!include DEFS.puml

actor "Operador" as OP
boundary "IHM"
participant "FIltragem de permissões" as Z
control Sistema as ST

/'
O sistema DEVE exibir alarmes de falha. Será considerado atendido
quando uma falha no MC (ex: motor travado) gerar uma mensagem textual
clara na IHM, acompanhada de um alarme sonoro e visual, em menos de 2
segundos após a ocorrência.
'/

'======================================================
'                      Inicio
'======================================================
'Permissões:
activate Z
activate ST
activate IHM
hnote over Z: Verifica os níveis de \n autorização do usuário.
OP -> IHM: Iniciar/Parar.
IHM -> ST: Se autorizado o processo inicia.
ST --> IHM
IHM -> ST
hnote over IHM: Fluxo dos dados.
hnote over ST: Processamento das informações.
hnote over ST: Em menos de 2s a \n notificação sonora/visual \n ocorre através da IHM.
IHM -> "OP": Visualização.
hnote over Z: Se o usuário não estiver \n autorizado a operação falha.
Z --> OP

'=====================================================
'Notas:
'=====================================================

legend top
**Diagrama de sequência - Módulo de Interface e Operação (MIO) - IHM Operacional**
end legend

footer


**Casos de Uso cobertos**:
 - **MIO-002** Exibição de Alarmes;
 - **MIO-003** Autenticação de Usuários;
end footer

@enduml