@startuml
!include DEFS.puml

actor "Operador"
boundary "IHM"
entity "Medição de grandezas" as MG
participant "MCU"

/'
O sistema DEVE exibir alarmes de falha. Será considerado atendido
quando uma falha no MC (ex: motor travado) gerar uma mensagem textual
clara na IHM, acompanhada de um alarme sonoro e visual, em menos de 2
segundos após a ocorrência.
'/

'======================================================
'                      Inicio
'======================================================
activate MCU
MG -> MCU: Repasse dos dados
MCU -> IHM: Exibição
IHM -> "Operador": Visualização
deactivate MCU

hnote over MCU: Processamento das informações

hnote over IHM: Em menos de 2s a notificação sonora/visual ocorre através da IHM


'=====================================================
'Notas:
'=====================================================

legend top
**Diagrama de sequência - Módulo de Interface e Operação (MIO) - IHM Operacional**
end legend

footer


**Casos de Uso cobertos**:
 - **MIO-002** Exibição de Alarmes
end footer



@enduml