@startuml
!include DEFS.puml

actor "Operador" as OP
boundary "IHM"
participant "FIltragem de permissões" as Z
control Sistema as ST

/'
O sistema DEVE possuir uma IHM local para operação. Será considerado
atendido quando a IHM permitir a um operador autenticado:

(a) Iniciar e parar o ciclo da linha; 
(b) Visualizar a contagem do turno em tempo real; 
(c) Visualizar o status do sistema (Operando, Parado, Falha).
'/

'======================================================
'                      Inicio
'======================================================
'Permissões:
activate Z
activate ST
activate IHM
hnote over Z: Verifica os níveis de \n autorização do usuário.
OP -> IHM: Iniciar/Parar ciclo de linha.
IHM -> ST: Se autorizado o processo inicia.
ST --> IHM: Contagem de turnos em tempo real
ST --> IHM: Status do sistema
'------------------------------------
'IHM:
hnote over IHM: Fluxo dos dados.
ST --> IHM
IHM -> ST
'------------------------------------

hnote over ST: Processamento das informações.
hnote over ST: Em menos de 2s a \n notificação sonora/visual \n ocorre através da IHM.
IHM -> "OP": Visualização.
hnote over Z: Se o usuário não estiver \n autorizado a operação falha.
Z --> OP

'=====================================================
'Notas:
'=====================================================

legend top
**Diagrama de sequência - Módulo de Interface e Operação (MIO) - IHM Operacional**
end legend

footer


**Casos de Uso cobertos**:
 - **MIO-001** Interface de Operação (IHM);
 - **MIO-003** Autenticação de Usuários;
end footer

@enduml