@startuml
'Parametros de dimensões:
scale 750 width
scale 750 height

'Parametros de cor:
skinparam backgroundColor #EEEBDC
skinparam handwritten true
skinparam sequenceArrowColor DeepSkyBlue
skinparam sequenceActorBorderColor DeepSkyBlue
skinparam sequenceLifeLineBorderColor blue
skinparam sequenceLifeLineBackgroundColor #A9DCDF
skinparam sequenceParticipantBorderColor DeepSkyBlue
skinparam sequenceParticipantBackgroundColor DodgerBlue
skinparam sequenceParticipantFontName Impact
skinparam sequenceParticipantFontSize 17
skinparam sequenceParticipantFontColor #A9DCDF
skinparam sequenceActorBackgroundColor aqua
skinparam sequenceActorFontColor DeepSkyBlue
skinparam sequenceActorFontSize 17
skinparam sequenceActorFontName Aapex

skinparam legendFontColor DodgerBlue
skinparam legendFontSize 16
skinparam legndFontName Arial

<style>
footer {
  HorizontalAlignment left
  FontSize 14
  FontColor DodgerBlue  
  FontName Arial
  Margin 20
  Padding 10
}
legend {
  FontSize 20
  FontColor DodgerBlue  
  FontName Arial
  Margin 20
  Padding 20
}
</style>

hide footbox

legend top
  **Diagrama de Sequência - Fluxo Principal**
end legend


'note top
'  Este é o título ou descrição do diagrama
'end note

actor "Sensor Óptico"

"Sensor Óptico" -> MCU: Detecta embalagem no início da Esteira
activate MCU #000000
MCU             -> MCU: Aciona dispositivo de manobra
MCU             -> Esteira: Liga Esteira
"Sensor Óptico" -> MCU: Detecta Embalagem no meio da Esteira
MCU             -> MCU: Incrementa Contador
MCU             -> Monitor: Envia dados para o IHM
MCU             -> "Módulo Edge": Envia dados para Nuvem
"Sensor Óptico" -> MCU: Detecta Embalagem no Fim da Esteira


footer
  **Casos de Uso cobertos:**
   - **MC-001** Controle da esteira e atuadores
   - **MC-002** Contagem de produtos de alta velocidade
   - **MC-005** Leitura de sensores analógicos e digitais
end footer

@enduml