@startuml

!include DEFS.puml

' --- Definições de atores/participants (aqui, no arquivo de lógica) ---
actor Operador
participant "Linha de produção" as A
participant "Contagem em tempo real" as B
participant "Status do sistema" as C

' ======================================================
'                      Inicio da lógica
' ======================================================
Operador -> A: Iniciar/Parar
activate A
A -> B: Enviar contagem
B -> C: Atualizar status
deactivate A

@enduml